### ISSUE TITLE
"No package matching 'libcurl3' is available" on Ubuntu 20.04

### ISSUE THREAD

**Issue by boldandbusted** [gsoft-inc/ansible-role-azure-devops-agent#39]
Tried installing on Ubuntu 20.04, and the latest version of this role from Ansible Galaxy, and it failed at this step:

Install dependencies...
  azdoagent failed | msg: No package matching 'libcurl3' is available

Happy to provide more info. Cheers!

**Comment by imphil** [comment]
Two things:

* Yes, the libcurl3 dependency should be libcurl4 for Ubuntu 18.04+.
* Since September, libcurl isn't needed any more at all (https://github.com/microsoft/azure-pipelines-agent/commit/cc985a827e957a7fba2d846d1ec934fde4cbc767#diff-032ed1f5f9a16122645695c0dc614f96bae48eb3c182bad2cef169b247e1e751). So you can actually remove the dependency altogether.

You can do those changes in the file `vars/dependencies-Ubuntu-20.yml` (https://github.com/gsoft-inc/ansible-role-azure-devops-agent/blob/master/vars/dependencies-Ubuntu-20.yml) and check if the agent installs and works as expected?

**Comment by pe-pe** [comment]
I've submitted pull request to resolve dependency by using libcurl4 - #41

**Comment by yohanb** [comment]
merged, thanks.
